sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: d0j05hT/T4e/5imRqDuY/sz0iYe0LOiYn8FeZL6nZKPDfUDnKw6Ux7ds4Nh327wvoUYV6/zSCbxdSCokl4wZ1AewFEjAEgtyCgDaoWNtPjhox28+xVjPQtkU1+qMU/Ec5Jjd7kUWaDCEQpDAhk6vgWdtOLz2LCzF2bqTP2CFxafzW9DcHTDspUdQ3hN4DBqKnSsqKpGuHA38XLioxDOaSexESUkEBJUNkxDmQNPP6kkYa48hfEyugZJyi5piNEgGokPRoTjEDZjgd7FWF+izYj7+N1xzp1kQ+pfTr4phnSVyeaf5+wycj6g3C7nKanxuZl72paORiun9PMqdO+KAmuDTnJzZMynqmHuq4+fMqXZnhLiHB1fsKR4Zt6h1b2AvTxSi1BFnuP61//WK9smfD7w0BlHxHr0Hw5CVoCQEzY14w0gx4v68aI/+Bdb6YxAU4oq16rljK/TBQKD8rqa9E6y4Qq5eG0HsPW1L3AtVrYfMP/2xZVvaQyGUxOeTsEAhR6Pnrl9SUm/w6eK1AY2GVvPoy/dpqUeUAuTkaX57lOMUG4seczdiPXPREwT/a06k9p5VFeaV7hF9ZY0rbzbySTEvzHZFP6oWmAHjj1epL7QnyLU95uRyAum5NZokzmEifAVi+egXF0XWa5qrKVNXGKO9JVn+m9ShMEDRxuzOS9w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Changed-Man-and-Other-Tales_3058
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy